export const products = [
  {
    id: 1,
    name: "Nike Air Max 270",
    photo: "/Nike_Air_Max 270.jpg",
    prix: 129.99,
    description: "Nike Air Max 270 — amorti léger et semelle Air grande taille",
    Stock: 4,
  },
  {
    id: 2,
    name: "Nike Air Force 1",
    photo: "/Nike_Air_Force_1.jpg",
    prix: 109.99,
    description: "Nike Air Force 1 — icône du basketball devenue classique streetwear",
    Stock: 8,
  },
  {
    id: 3,
    name: "Adidas Samba OG",
    photo: "/Adidas_Samba_OG.jpg",
    prix: 89.99,
    description: "Adidas Samba OG — silhouette légendaire née sur les terrains en salle",
    Stock: 6,
  },
  {
    id: 4,
    name: "Nike Air Force 1 Flyknit 2.0",
    photo: "/AIR+FORCE+1+FLYKNIT+2.0.jpg",
    prix: 99.99,
    description: "Nike Air Force 1 Flyknit 2.0 — tige en mesh ultra légère et respirante",
    Stock: 5,
  },
  {
    id: 5,
    name: "Air Jordan 1 Mid",
    photo: "/AIR+JORDAN+1+MID.jpg",
    prix: 179.99,
    description: "Air Jordan 1 Mid — le style légendaire de Michael Jordan revisité",
    Stock: 5,
  },
  {
    id: 6,
    name: "Puma Softride Enzo 5.0",
    photo: "/Men's_Puma_Softride_Enzo.jpg",
    prix: 69.99,
    description: "Puma Softride Enzo 5.0 — semelle ultra douce pour un confort quotidien",
    Stock: 7,
  },
  {
    id: 7,
    name: "Converse Chuck Taylor All Star",
    photo: "/CONVERSE_CHUCK_TAYLOR_ALL_STAR_LIFT.JPG",
    prix: 59.99,
    description: "Converse Chuck Taylor All Star — la toile iconique portée depuis 1917",
    Stock: 10,
  },
  {
    id: 8,
    name: "Puma RS-X",
    photo: "/Puma_RS_X.jpg",
    prix: 119.99,
    description: "Puma RS-X — design futuriste inspiré des chaussures running des années 80",
    Stock: 6,
  },
  {
    id: 9,
    name: "New Balance 550",
    photo: "/New-Balance-550-White-Green-Product.jpg",
    prix: 139.99,
    description: "New Balance 550 — silhouette basketball rétro remise au goût du jour",
    Stock: 4,
  },
  {
    id: 10,
    name: "Under Armour Curry 11 Team",
    photo: "/Under Armour Adult Curry 11 Team.jpg",
    prix: 159.99,
    description: "Under Armour Curry 11 — la chaussure signature de Stephen Curry haute performance",
    Stock: 5,
  },
];


